Repository Nexters-PIMO/FIMO_iOS, pull requests merged in 2023-06, with the labels that each got.

#58 [feature,fix/#38] 딥링크 및 앱 아이콘 세팅, 카카오톡 앱 로그인 안되는 이슈 해결
  .gitignore
  PIMO/PIMO.entitlements
  PIMO/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  PIMO/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  PIMO/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  PIMO/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  PIMO/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  PIMO/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  PIMO/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  PIMO/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  PIMO/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  PIMO/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  PIMO/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  PIMO/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  PIMO/Sources/App/AppDelegate.swift
  PIMO/Sources/App/PIMOApp.swift
  PIMO/Sources/Core/Extension/NotificationName.swift
  PIMO/Sources/Core/Extension/String+Date.swift
  PIMO/Sources/Core/Extension/String+regex.swift
  PIMO/Sources/Core/Extension/UIImage+.swift
  PIMO/Sources/Core/Extension/UINavigationController+.swift
  PIMO/Sources/Core/Extension/UIScreen+.swift
  PIMO/Sources/Core/Extension/View+EdgeBorder.swift
  PIMO/Sources/Core/Extension/View+if.swift
  PIMO/Sources/Core/Modifiers/CornerRadiusStyle.swift
  PIMO/Sources/Core/Modifiers/Popup/BackPopup.swift
  PIMO/Sources/Core/Modifiers/Popup/ClosePopup.swift
  PIMO/Sources/Core/Modifiers/Popup/LogoutPopup.swift
  PIMO/Sources/Core/Modifiers/Popup/ModifyProfileBackPopup.swift
  PIMO/Sources/Core/Modifiers/Popup/RemovePopup.swift
  PIMO/Sources/Core/Modifiers/Popup/WithdrawalPopup.swift
  PIMO/Sources/Core/Modifiers/View+.swift
  PIMO/Sources/Core/Utill/TTSManager.swift
  PIMO/Sources/Core/Utill/UserUtill.swift
  PIMO/Sources/DSKit/Components/BottomSheet/BottomSheetStore.swift
  PIMO/Sources/DSKit/Components/BottomSheet/BottomSheetView.swift
  PIMO/Sources/DSKit/Components/CustomBackButton.swift
  PIMO/Sources/DSKit/Components/CustomDivider.swift
  PIMO/Sources/DSKit/Components/ImagePicker.swift
  PIMO/Sources/DSKit/Components/Navigation/CustomNavigationBar.swift
  PIMO/Sources/DSKit/Components/Navigation/NavigationBarShadow.swift
  PIMO/Sources/DSKit/Components/Views/GifImageView.swift
  PIMO/Sources/DSKit/Components/Views/LoadingView.swift
  PIMO/Sources/DSKit/Components/Views/PopupView.swift
  PIMO/Sources/DSKit/Components/Views/ToastView.swift
  PIMO/Sources/Network/Client/FeedClient.swift
  PIMO/Sources/View/TabBar/Components/TabBar.swift
  Project.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/InfoPlist.swift
Labels: feature, fix

#59 [fix/#21] 부자연스러운 온보딩 화면 수정
  PIMO/Sources/View/Onboarding/OnboardingView.swift
  PIMO/Sources/View/UnAuthenticated/UnAuthenticatedStore.swift
Labels: fix

#64 [feature] 네트워크 재 연결(로그인, 프로필, 팔로우 관련 씬 구현)
  FIMO/Sources/App/DataFlow/AppStore.swift
  FIMO/Sources/App/DataFlow/UserStore.swift
  FIMO/Sources/App/Logger.swift
  FIMO/Sources/Core/Modifiers/Popup/FriendshipPopup.swift
  FIMO/Sources/DSKit/Components/Views/PopupView.swift
  FIMO/Sources/Model/Type/ProfileSetting/CheckValidationType.swift
  FIMO/Sources/Model/UIModel/FMAuth/FMSighUp.swift
  FIMO/Sources/Model/UIModel/FMFollow/FMFollowMe.swift
  FIMO/Sources/Model/UIModel/FMFollow/FMFriend.swift
  FIMO/Sources/Model/UIModel/FMFollow/FriendType.swift
  FIMO/Sources/Model/UIModel/FMFollow/FriendshipDescriptionType.swift
  FIMO/Sources/Model/UIModel/FMServer/FMServerDescription.swift
  FIMO/Sources/Model/UIModel/FMUser/FMProfile.swift
  FIMO/Sources/Network/Client/FriendsClient.swift
  FIMO/Sources/Network/Client/LoginClient.swift
  FIMO/Sources/Network/Client/ProfileClient.swift
  FIMO/Sources/Network/DTO/FMFollow/FMFriendDTO.swift
  FIMO/Sources/Network/DTO/FMServerDescriptionDTO.swift
  FIMO/Sources/Network/RequestModel/FMFollow/FMFollowMeRequest.swift
  FIMO/Sources/Network/RequestModel/FMFollow/FMFollowingRequest.swift
  FIMO/Sources/Network/RequestModel/FMFollow/FMUnfollowingRequest.swift
  FIMO/Sources/Network/RequestModel/FMUser/FMUserProfileUpdateRequest.swift
  FIMO/Sources/Network/RequestModel/FMUser/FMUserValidateRequest.swift
  FIMO/Sources/View/Archive/ArchiveStore.swift
  FIMO/Sources/View/Archive/ArchiveView.swift
  FIMO/Sources/View/Archive/Components/ArchiveTopBar.swift
  FIMO/Sources/View/Friends/FriendsListStore.swift
  FIMO/Sources/View/Friends/FriendsListView.swift
  FIMO/Sources/View/Home/HomeStore.swift
  FIMO/Sources/View/Login/Components/KakaoLoginButton.swift
  FIMO/Sources/View/Login/LoginStore.swift
  FIMO/Sources/View/Login/LoginView.swift
  FIMO/Sources/View/ProfileSetting/ProfilePictureSettingView.swift
  FIMO/Sources/View/ProfileSetting/ProfileSettingStore.swift
  FIMO/Sources/View/Setting/SettingStore.swift
  FIMO/Sources/View/Setting/SettingView.swift
  FIMO/Sources/View/TabBar/TabBarStore.swift
  FIMO/Sources/View/TabBar/TabBarView.swift
  FIMO/Sources/View/UnAuthenticated/UnAuthenticatedStore.swift
Labels: feature

#70 [feature, setting/#65, #66] 네트워크 연결, 디자인 재적용, tuist 의존성 변경 등
  .package.resolved
  FIMO/Sources/App/GoogleAnalytics.swift
  FIMO/Sources/DSKit/Components/Views/LoadingView.swift
  FIMO/Sources/Model/Type/Onboarding/OnboardingPageType.swift
  FIMO/Sources/Model/UIModel/Friend/FriendsListSortType.swift
  FIMO/Sources/Network/Client/FriendsClient.swift
  FIMO/Sources/Network/Client/PostClient.swift
  FIMO/Sources/Network/RequestModel/FMFollow/FMFollowMeRequest.swift
  FIMO/Sources/View/Acknow/AcknowView.swift
  FIMO/Sources/View/Friends/FriendsListStore.swift
  FIMO/Sources/View/Friends/FriendsListView.swift
  FIMO/Sources/View/Login/Components/AppleLoginButton.swift
  FIMO/Sources/View/Login/Components/KakaoLoginButton.swift
  FIMO/Sources/View/Login/LoginStore.swift
  FIMO/Sources/View/Login/LoginView.swift
  FIMO/Sources/View/Onboarding/FirstOnboardingView.swift
  FIMO/Sources/View/Onboarding/OnboardingCollectionView.swift
  FIMO/Sources/View/Onboarding/OnboardingStore.swift
  FIMO/Sources/View/Onboarding/OnboardingView.swift
  FIMO/Sources/View/Onboarding/OtherOnboardingView.swift
  FIMO/Sources/View/ProfileSetting/ModifyProfileView.swift
  FIMO/Sources/View/Setting/SettingStore.swift
  FIMO/Sources/View/Setting/SettingView.swift
  FIMO/Sources/View/TabBar/TabBarStore.swift
  FIMO/Sources/View/Upload/Model/UploadImage.swift
  FIMO/Sources/View/Upload/UploadStore.swift
  FIMO/Sources/View/Upload/UploadView.swift
  Plugins/EnvPlugin/ProjectDescriptionHelpers/Environment.swift
  Plugins/EnvPlugin/ProjectDescriptionHelpers/SettingsDictionary+.swift
  Project.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: feature, setting
