Repository Nexters-PIMO/FIMO_iOS, pull requests merged in 2023-03, with the labels that each got.

#35 [Feature/#27] 아카이브 화면 구현
  PIMO/Resources/Assets.xcassets/Feeds/Contents.json
  PIMO/Resources/Assets.xcassets/Feeds/archive_logo.imageset/Contents.json
  PIMO/Resources/Assets.xcassets/Feeds/archive_logo.imageset/archive_logo.svg
  PIMO/Resources/Assets.xcassets/Feeds/back.imageset/Contents.json
  PIMO/Resources/Assets.xcassets/Feeds/back.imageset/back.svg
  PIMO/Resources/Assets.xcassets/Feeds/basic_mode.imageset/Contents.json
  PIMO/Resources/Assets.xcassets/Feeds/basic_mode.imageset/basic_mode.svg
  PIMO/Resources/Assets.xcassets/Feeds/basic_mode_selected.imageset/Contents.json
  PIMO/Resources/Assets.xcassets/Feeds/basic_mode_selected.imageset/basic_mode_selected.svg
  PIMO/Resources/Assets.xcassets/Feeds/both_friend.imageset/Contents.json
  PIMO/Resources/Assets.xcassets/Feeds/both_friend.imageset/both_friend.png
  PIMO/Resources/Assets.xcassets/Feeds/both_friend.imageset/both_friend@2x.png
  PIMO/Resources/Assets.xcassets/Feeds/both_friend.imageset/both_friend@3x.png
  PIMO/Resources/Assets.xcassets/Feeds/feed_empty.imageset/Contents.json
  PIMO/Resources/Assets.xcassets/Feeds/feed_empty.imageset/feed_empty.png
  PIMO/Resources/Assets.xcassets/Feeds/feed_empty.imageset/feed_empty@2x.png
  PIMO/Resources/Assets.xcassets/Feeds/feed_empty.imageset/feed_empty@3x.png
  PIMO/Resources/Assets.xcassets/Feeds/friendlist.imageset/Contents.json
  PIMO/Resources/Assets.xcassets/Feeds/friendlist.imageset/friendlist.svg
  PIMO/Resources/Assets.xcassets/Feeds/grid_mode.imageset/Contents.json
  PIMO/Resources/Assets.xcassets/Feeds/grid_mode.imageset/grid_mode.svg
  PIMO/Resources/Assets.xcassets/Feeds/grid_mode_selected.imageset/Contents.json
  PIMO/Resources/Assets.xcassets/Feeds/grid_mode_selected.imageset/grid_mode_selected.svg
  PIMO/Resources/Assets.xcassets/Feeds/me_friend.imageset/Contents.json
  PIMO/Resources/Assets.xcassets/Feeds/me_friend.imageset/me_friend.png
  PIMO/Resources/Assets.xcassets/Feeds/me_friend.imageset/me_friend@2x.png
  PIMO/Resources/Assets.xcassets/Feeds/me_friend.imageset/me_friend@3x.png
  PIMO/Resources/Assets.xcassets/Feeds/neither_friend.imageset/Contents.json
  PIMO/Resources/Assets.xcassets/Feeds/neither_friend.imageset/neither_friend.png
  PIMO/Resources/Assets.xcassets/Feeds/neither_friend.imageset/neither_friend@2x.png
  PIMO/Resources/Assets.xcassets/Feeds/neither_friend.imageset/neither_friend@3x.png
  PIMO/Resources/Assets.xcassets/Feeds/other_friend.imageset/Contents.json
  PIMO/Resources/Assets.xcassets/Feeds/other_friend.imageset/other_friend.png
  PIMO/Resources/Assets.xcassets/Feeds/other_friend.imageset/other_friend@2x.png
  PIMO/Resources/Assets.xcassets/Feeds/other_friend.imageset/other_friend@3x.png
  PIMO/Resources/Localizable.strings
  PIMO/Sources/Model/Feed/Archive.swift
  PIMO/Sources/Model/Feed/ArchiveInfo.swift
  PIMO/Sources/Model/Feed/Feed.swift
  PIMO/Sources/Model/Feed/Profile.swift
  PIMO/Sources/Model/Feed/Temp.swift
  PIMO/Sources/Network/ArchiveClient.swift
  PIMO/Sources/Network/HomeClient.swift
  PIMO/Sources/Network/ProfileClient.swift
  PIMO/Sources/View/Archive/ArchiveStore.swift
  PIMO/Sources/View/Archive/ArchiveView.swift
  PIMO/Sources/View/Archive/Components/ArchiveEmptyView.swift
  PIMO/Sources/View/Archive/Components/ArchiveTopBar.swift
  PIMO/Sources/View/Feed/FeedStore.swift
  PIMO/Sources/View/Feed/FeedTextImageView.swift
  PIMO/Sources/View/Home/Components/HomeTopBar.swift
  PIMO/Sources/View/Home/HomeStore.swift
  PIMO/Sources/View/MyFeed/MyFeedStore.swift
  PIMO/Sources/View/MyFeed/MyFeedView.swift
  PIMO/Sources/View/TabBar/TabBarStore.swift
  PIMO/Sources/View/TabBar/TabBarView.swift
Labels: feature

#33 [Feature/#21] 프로필 수정 화면 구현
  PIMO/Resources/Assets.xcassets/ProfileSetting/edit.imageset/Contents.json
  PIMO/Resources/Assets.xcassets/ProfileSetting/edit.imageset/edit.svg
  PIMO/Sources/Model/ProfileSetting/CheckValidationType.swift
  PIMO/Sources/Model/ProfileSetting/ProfileSettingFieldType.swift
  PIMO/Sources/View/ProfileSetting/ModifyProfileView.swift
  PIMO/Sources/View/ProfileSetting/ProfileSettingStore.swift
Labels: feature

#31 [Feature/#30] 세팅 화면 구현
  PIMO/Resources/Localizable.strings
  PIMO/Sources/View/Modifier/BackPopup.swift
  PIMO/Sources/View/Modifier/LogoutPopup.swift
  PIMO/Sources/View/Modifier/WithdrawalPopup.swift
  PIMO/Sources/View/Setting/SettingStore.swift
  PIMO/Sources/View/Setting/SettingView.swift
  PIMO/Sources/View/Setting/TermsOfUseView.swift
Labels: feature

#36 [Feature/#28] 피드 화면 추가 구현
  PIMO/Resources/Localizable.strings
  PIMO/Sources/App/User/UserDefaultsKeys.swift
  PIMO/Sources/App/Utill/TTSUtil.swift
  PIMO/Sources/App/Utill/UserUtill.swift
  PIMO/Sources/View/Archive/ArchiveStore.swift
  PIMO/Sources/View/Archive/ArchiveView.swift
  PIMO/Sources/View/Feed/Components/FeedTextImageView.swift
  PIMO/Sources/View/Feed/FeedStore.swift
  PIMO/Sources/View/Feed/FeedView.swift
  PIMO/Sources/View/Home/HomeStore.swift
  PIMO/Sources/View/Home/HomeView.swift
  PIMO/Sources/View/Upload/UploadView.swift
Labels: feature

#39 [feature/#34] 네비게이션 처리, 네비게이션 임베디드에 따른 뷰 수정, 온보딩 화면 이미지 추가 등
  PIMO/Resources/Assets.xcassets/App/Contents.json
  PIMO/Resources/Assets.xcassets/App/LaunchScreenLogo.imageset/Contents.json
  PIMO/Resources/Assets.xcassets/App/LaunchScreenLogo.imageset/Frame 61185.svg
  PIMO/Resources/Assets.xcassets/Onboarding/onboardingBackgroundFour.imageset/Contents.json
  PIMO/Resources/Assets.xcassets/Onboarding/onboardingBackgroundFour.imageset/onboardingBackgroundFour.jpg
  PIMO/Resources/Assets.xcassets/Onboarding/onboardingBackgroundFour.imageset/onboardingBackgroundFour@2x.jpg
  PIMO/Resources/Assets.xcassets/Onboarding/onboardingBackgroundFour.imageset/onboardingBackgroundFour@3x.jpg
  PIMO/Resources/Assets.xcassets/Onboarding/onboardingBackgroundOne.imageset/Contents.json
  PIMO/Resources/Assets.xcassets/Onboarding/onboardingBackgroundOne.imageset/onboardingBackground.jpg
  PIMO/Resources/Assets.xcassets/Onboarding/onboardingBackgroundOne.imageset/onboardingBackground@2x.jpg
  PIMO/Resources/Assets.xcassets/Onboarding/onboardingBackgroundOne.imageset/onboardingBackground@3x.jpg
  PIMO/Resources/Assets.xcassets/Onboarding/onboardingBackgroundThree.imageset/Contents.json
  PIMO/Resources/Assets.xcassets/Onboarding/onboardingBackgroundThree.imageset/onboardingBackgroundThree.jpg
  PIMO/Resources/Assets.xcassets/Onboarding/onboardingBackgroundThree.imageset/onboardingBackgroundThree@2x.jpg
  PIMO/Resources/Assets.xcassets/Onboarding/onboardingBackgroundThree.imageset/onboardingBackgroundThree@3x.jpg
  PIMO/Resources/Assets.xcassets/Onboarding/onboardingBackgroundTwo.imageset/Contents.json
  PIMO/Resources/Assets.xcassets/Onboarding/onboardingBackgroundTwo.imageset/onboardingBackgroundTwo.jpg
  PIMO/Resources/Assets.xcassets/Onboarding/onboardingBackgroundTwo.imageset/onboardingBackgroundTwo@2x.jpg
  PIMO/Resources/Assets.xcassets/Onboarding/onboardingBackgroundTwo.imageset/onboardingBackgroundTwo@3x.jpg
  PIMO/Resources/Assets.xcassets/Onboarding/whitefimo.imageset/Contents.json
  PIMO/Resources/Assets.xcassets/Onboarding/whitefimo.imageset/Group (1).svg
  PIMO/Resources/Localizable.strings
  PIMO/Sources/App/DataFlow/AppStore.swift
  PIMO/Sources/App/LaunchScreen.swift
  PIMO/Sources/App/PIMOApp.swift
  PIMO/Sources/Model/Base/TrailingItemType.swift
  PIMO/Sources/Model/Friend/FriendsList.swift
  PIMO/Sources/Model/Onboarding/OnboardingPageType.swift
  PIMO/Sources/Network/FriendsClient.swift
  PIMO/Sources/View/Archive/ArchiveStore.swift
  PIMO/Sources/View/Archive/ArchiveView.swift
  PIMO/Sources/View/Base/CustomBackButton.swift
  PIMO/Sources/View/Base/CustomNavigationBar.swift
  PIMO/Sources/View/Base/NavigationBarShadow.swift
  PIMO/Sources/View/Friends/FriendsListStore.swift
  PIMO/Sources/View/Friends/FriendsListView.swift
  PIMO/Sources/View/Home/Components/HomeTopBar.swift
  PIMO/Sources/View/Home/HomeStore.swift
  PIMO/Sources/View/Home/HomeView.swift
  PIMO/Sources/View/Login/LoginStore.swift
  PIMO/Sources/View/Login/LoginView.swift
  PIMO/Sources/View/Onboarding/OnboardingDescriptionView.swift
  PIMO/Sources/View/Onboarding/OnboardingStore.swift
  PIMO/Sources/View/Onboarding/OnboardingView.swift
  PIMO/Sources/View/Onboarding/UnAuthenticatedStore.swift
  PIMO/Sources/View/ProfileSetting/ArchiveSettingView.swift
  PIMO/Sources/View/ProfileSetting/CompleteSettingView.swift
  PIMO/Sources/View/ProfileSetting/NicknameSettingView.swift
  PIMO/Sources/View/ProfileSetting/ProfilePictureSettingView.swift
  PIMO/Sources/View/ProfileSetting/ProfileSettingStore.swift
  PIMO/Sources/View/Setting/SettingStore.swift
  PIMO/Sources/View/Setting/SettingView.swift
  PIMO/Sources/View/Setting/TermsOfUseView.swift
  PIMO/Sources/View/TabBar/TabBarStore.swift
  PIMO/Sources/View/extension/UINavigationController+.swift
Labels: feature

#43 [feature/#42] 네트워크 관련 추가 구현
  PIMO/Sources/Model/Feed/MyProfile.swift
  PIMO/Sources/Model/Feed/Profile.swift
  PIMO/Sources/Model/Feed/Temp.swift
  PIMO/Sources/Network/Base/BaseNetwork.swift
  PIMO/Sources/Network/Base/HTTPHeader.swift
  PIMO/Sources/Network/Base/InterceptorAuthenticator.swift
  PIMO/Sources/Network/Base/NetworkEnvironment.swift
  PIMO/Sources/Network/Base/NetworkError.swift
  PIMO/Sources/Network/Base/Requestable.swift
  PIMO/Sources/Network/LoginClient.swift
  PIMO/Sources/Network/ProfileClient.swift
  PIMO/Sources/Network/RequestModel/Users/MyProfileRequest.swift
  PIMO/Sources/View/Archive/ArchiveStore.swift
  PIMO/Sources/View/Archive/ArchiveView.swift
  PIMO/Sources/View/Feed/FeedView.swift
  PIMO/Sources/View/Home/HomeStore.swift
  PIMO/Sources/View/TabBar/TabBarStore.swift
  PIMO/Sources/View/TabBar/TabBarView.swift
  Tuist/ProjectDescriptionHelpers/InfoPlist.swift
Labels: feature, fix

#45 [fix/ #42] network JSON 예외처리, 분기처리 수정
  PIMO/Sources/Network/Base/BaseNetwork.swift
Labels: fix

#46 [Feature/#40] AUDIO 기능 추가 구현
  .swiftlint.yml
  PIMO/Resources/Assets.xcassets/Feed/audio.imageset/audio.png
  PIMO/Resources/Assets.xcassets/Feed/audio.imageset/audio@2x.png
  PIMO/Resources/Assets.xcassets/Feed/audio.imageset/audio@3x.png
  PIMO/Resources/Assets.xcassets/Feed/audio_selected.imageset/Contents.json
  PIMO/Resources/Assets.xcassets/Feed/audio_selected.imageset/audio_selected.png
  PIMO/Resources/Assets.xcassets/Feed/audio_selected.imageset/audio_selected@2x.png
  PIMO/Resources/Assets.xcassets/Feed/audio_selected.imageset/audio_selected@3x.png
  PIMO/Resources/audio_selected.gif
  PIMO/Sources/App/Extension/NotificationName.swift
  PIMO/Sources/App/PIMOApp.swift
  PIMO/Sources/App/Utill/TTSUtil.swift
  PIMO/Sources/Network/FeedClient.swift
  PIMO/Sources/View/Archive/ArchiveStore.swift
  PIMO/Sources/View/Base/GifImageView.swift
  PIMO/Sources/View/Feed/FeedStore.swift
  PIMO/Sources/View/Feed/FeedView.swift
  PIMO/Sources/View/Home/HomeStore.swift
  Project.swift
  Tuist/Dependencies.swift
Labels: feature

#48 [Feature/#37] 피드 바텀시트 구현
  PIMO/Sources/Model/Base/BottomSheetType.swift
  PIMO/Sources/View/Archive/ArchiveStore.swift
  PIMO/Sources/View/Archive/ArchiveView.swift
  PIMO/Sources/View/BottomSheet/BottomSheetStore.swift
  PIMO/Sources/View/BottomSheet/BottomSheetView.swift
  PIMO/Sources/View/Components/PopupView.swift
  PIMO/Sources/View/Feed/FeedStore.swift
  PIMO/Sources/View/Home/HomeStore.swift
  PIMO/Sources/View/Home/HomeView.swift
  PIMO/Sources/View/Modifier/ClosePopup.swift
  PIMO/Sources/View/Modifier/RemovePopup.swift
  PIMO/Sources/View/TabBar/TabBarStore.swift
  PIMO/Sources/View/TabBar/TabBarView.swift
Labels: feature

#49 [Feature/#47] 피드(홈) 네트워크 연결
  PIMO/Resources/Localizable.strings
  PIMO/Sources/App/Client/UserClient.swift
  PIMO/Sources/App/Extension/String+.swift
  PIMO/Sources/App/Utill/UserUtill.swift
  PIMO/Sources/Model/Archive/Archive.swift
  PIMO/Sources/Model/Archive/ArchiveInfo.swift
  PIMO/Sources/Model/Feed/Feed.swift
  PIMO/Sources/Model/Feed/Profile.swift
  PIMO/Sources/Model/Feed/Temp.swift
  PIMO/Sources/Network/Base/BaseNetwork.swift
  PIMO/Sources/Network/Base/HTTPHeader.swift
  PIMO/Sources/Network/Base/Requestable.swift
  PIMO/Sources/Network/Client/ArchiveClient.swift
  PIMO/Sources/Network/Client/FeedClient.swift
  PIMO/Sources/Network/Client/FriendsClient.swift
  PIMO/Sources/Network/Client/HomeClient.swift
  PIMO/Sources/Network/Client/LoginClient.swift
  PIMO/Sources/Network/Client/ProfileClient.swift
  PIMO/Sources/Network/DTO/FeedDTO.swift
  PIMO/Sources/Network/DTO/TextImageDTO.swift
  PIMO/Sources/Network/RequestModel/FeedRequest.swift
  PIMO/Sources/Network/RequestModel/FeedsRequest.swift
  PIMO/Sources/Network/RequestModel/HomeRequest.swift
  PIMO/Sources/Network/RequestModel/ProfileRequest.swift
  PIMO/Sources/Network/RequestModel/Users/MyProfileRequest.swift
  PIMO/Sources/View/Archive/ArchiveView.swift
  PIMO/Sources/View/Archive/Components/ArchiveEmptyView.swift
  PIMO/Sources/View/BottomSheet/BottomSheetView.swift
  PIMO/Sources/View/Feed/FeedStore.swift
  PIMO/Sources/View/Feed/FeedView.swift
  PIMO/Sources/View/Home/HomeStore.swift
  PIMO/Sources/View/Home/HomeView.swift
  PIMO/Sources/View/Login/Components/KakaoLoginButton.swift
  PIMO/Sources/View/Login/LoginStore.swift
  PIMO/Sources/View/Login/LoginView.swift
Labels: feature

#52 [feature/#30, #51] 오픈소스 라이센스 표시 라이브러리 추가, imgur 네트워크 연결
  PIMO/Sources/Model/Imgur/ImgurErrorModel.swift
  PIMO/Sources/Model/Imgur/ImgurImageModel.swift
  PIMO/Sources/Network/Base/BaseNetwork.swift
  PIMO/Sources/Network/Base/HTTPHeader.swift
  PIMO/Sources/Network/Base/ImgurRequestable.swift
  PIMO/Sources/Network/Base/ImgurUploadBodyType.swift
  PIMO/Sources/Network/Base/NetworkError.swift
  PIMO/Sources/Network/Client/ImgurImageClient.swift
  PIMO/Sources/Network/RequestModel/ImgurImageUploadModel.swift
  PIMO/Sources/View/Acknow/AcknowListView.swift
  PIMO/Sources/View/Acknow/AcknowView.swift
  PIMO/Sources/View/Archive/ArchiveStore.swift
  PIMO/Sources/View/Archive/ArchiveView.swift
  PIMO/Sources/View/Home/HomeStore.swift
  PIMO/Sources/View/Home/HomeView.swift
  PIMO/Sources/View/ProfileSetting/ModifyProfileView.swift
  PIMO/Sources/View/ProfileSetting/ProfilePictureSettingView.swift
  PIMO/Sources/View/ProfileSetting/ProfileSettingStore.swift
  Project.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: feature

#53 [feature/ #21] 프로필 기입, 수정 관련 네트워크 연결 등
  PIMO/Sources/Network/Client/ProfileClient.swift
  PIMO/Sources/Network/RequestModel/ProfileCheckRequest.swift
  PIMO/Sources/Network/RequestModel/ProfileRequest.swift
  PIMO/Sources/View/Archive/ArchiveStore.swift
  PIMO/Sources/View/Archive/ArchiveView.swift
  PIMO/Sources/View/Base/CustomNavigationBar.swift
  PIMO/Sources/View/Home/HomeStore.swift
  PIMO/Sources/View/Home/HomeView.swift
  PIMO/Sources/View/Modifier/ModifyProfileBackPopup.swift
  PIMO/Sources/View/ProfileSetting/ModifyProfileView.swift
  PIMO/Sources/View/ProfileSetting/ProfilePictureSettingView.swift
  PIMO/Sources/View/ProfileSetting/ProfileSettingStore.swift
  PIMO/Sources/View/TabBar/TabBarStore.swift
  PIMO/Sources/View/TabBar/TabBarView.swift
  Tuist/ProjectDescriptionHelpers/InfoPlist.swift
Labels: feature
